name: Power On

on:
  workflow_dispatch:
    inputs:
      mac:
        description: 'MAC Address'
        required: true
      address:
        description: 'IP Address'
        required: true
      port:
        description: 'Port'
        required: false

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
      - run: bundle install
      - run: ruby power_on.rb
        env:
          MAC: ${{ inputs.mac || secrets.MAC }}
          ADDRESS: ${{ inputs.address || secrets.ADDRESS }}
          PORT: ${{ inputs.port || secrets.PORT }}