name: Power On

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/30 * * * *'

jobs:
  execute:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: false
      - run: bundle install
      - run: ruby power_on.rb
        env:
          MAC: ${{ secrets.MAC }}
          ADDRESS: ${{ secrets.ADDRESS }}
          PORT: ${{ secrets.PORT }}
